export const options = {
  aroma: 'Pleasing smell',
  pepper: "Salt's partner",
  halt: 'put a stop to',
  jump: 'Rise suddenly ',
  shuffle: 'Mix cards up ',
  combine: 'Add; Mix',
  chaos: 'Total disorder',
  labyrinth: 'Maze',
  disturb: 'Interrupt; upset ',
  shift: 'Move; Period of word',
  machine: 'Device or appliance',
  Python: 'Programming Language',
  Guitar: 'A Musical Instrument',
  Aim: 'A Purpose Or Intention',
  Venus: 'Planet Of Our Solar System',
  Gold: 'A Yellow Precious Metal',
  Ebay: 'Online Shopping Site',
  Golang: 'Programming Language',
  Coding: 'Related To Programming',
  Avatar: 'Epic Science Fiction Film',
  Map: 'Diagram Represent Of An Area',
  Island: 'Land Surrounded By Water',
  Chess: 'Related To A Indoor Game',
  Github: 'Code Hosting Platform',
  Png: 'A Image File Format',
  Silver: 'Precious Greyish-White Metal',
  Gpu: 'Computer Component',
  Java: 'Programming Language',
  Google: 'Famous Search Engine',
  Venice: 'Famous City Of Waters',
  Mysql: 'A Relational Database System',
  Flute: 'A Musical Instrument',
  Mars: 'Planet Of Our Solar System',
  Proxy: 'Related To Server Application',
  Email: 'Related To Exchanging Message',
  Html: 'Markup Language For The Web',
  Search: 'Act To Find Something',
};
